[env:esp32dev]
platform = espressif32 @ 4.2.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; FORCE the compiler to accept the old library code
build_flags = 
    -fpermissive
    -Wno-write-strings
    -D VID=0x303A
    -D PID=0x3000
    -D BLE_GAMEPAD_DEVICE_NAME="\"ESP32 Manette Gyroscope\""
    -D BLE_GAMEPAD_DEVICE_MANUFACTURER="\"Espressif\""
    -UPID

lib_deps = 
    lemmingdev/ESP32-BLE-Gamepad @ ^0.5.2
    ; We pin this version to prevent conflicts
    h2zero/NimBLE-Arduino @ ^1.4.1
    ; adafruit/Adafruit MPU6050
    ; adafruit/Adafruit Unified Sensor
    electroniccats/MPU6050 @ ^1.3.1